# Copyright (c) UBC-DSCI Development Team
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=ubcmds/dsci-011:v0.32.0

FROM $BASE_CONTAINER

LABEL maintainer="Tiffany Timbers <tiffany.timbers@gmail.com>"

COPY rm-merge-shortcut.py /tmp/user-settings/\@jupyterlab/shortcuts-extension/shortcuts.jupyterlab-settings
